apiVersion: v1
kind: Service
metadata:
  name: oracle
  labels:
    app.kubernetes.io/name: oracle
spec:
  selector:
    app.kubernetes.io/name: oracle
  ports:
    - name: oracle
      port: 1521
      targetPort: 1521
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oracle
  labels:
    app.kubernetes.io/name: oracle
spec:
  serviceName: oracle
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: oracle
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oracle
    spec:
      containers:
        - name: oracle
          image: gvenzl/oracle-xe@sha256:ecdf4302ac3d134e1bac5ef6e0c223c2d0f4d4d2b6d551aa79b2346f1ab8f792
          ports:
            - name: oracle
              containerPort: 1521
          env:
            - name: ORACLE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: docky-secret
                  key: ORACLE_PASSWORD
            - name: APP_USER
              valueFrom:
                secretKeyRef:
                  name: docky-secret
                  key: ORACLE_APP_USER
            - name: APP_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: docky-secret
                  key: ORACLE_APP_USER_PASSWORD
          volumeMounts:
            - name: oracle-data
              mountPath: /opt/oracle/oradata
          readinessProbe:
            tcpSocket:
              port: 1521
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 60
          livenessProbe:
            tcpSocket:
              port: 1521
            initialDelaySeconds: 180
            periodSeconds: 20
            failureThreshold: 12
          resources:
            requests:
              cpu: "500m"
              memory: 2Gi
            limits:
              memory: 4Gi
      volumes:
        - name: oracle-data
          persistentVolumeClaim:
            claimName: oracle-data
