apiVersion: v1
kind: ConfigMap
metadata:
  name: docky-app-config
data:
  APP_CORS_ALLOWED_ORIGIN_PATTERNS: "https://staging.docky.co.kr"
  GOOGLE_REDIRECT_URI: "https://staging.docky.co.kr/login/oauth2/code/google"
  NAVER_REDIRECT_URI: "https://staging.docky.co.kr/login/oauth2/code/naver"
  S3_PRESIGNED_PUBLIC_ENDPOINT: "https://staging.docky.co.kr"
