apiVersion: v1
kind: Secret
metadata:
  name: docky-secret
  namespace: docky
type: Opaque
stringData:
  CLOUDFLARE_TUNNEL_TOKEN: "replace-me"
  ORACLE_PASSWORD: "replace-me"
  ORACLE_APP_USER: "SCOTT_V1"
  ORACLE_APP_USER_PASSWORD: "replace-me"
  SPRING_DATASOURCE_USERNAME: "SCOTT_V1"
  SPRING_DATASOURCE_PASSWORD: "replace-me"
  MINIO_ROOT_USER: "replace-me"
  MINIO_ROOT_PASSWORD: "replace-me"
  S3_ACCESS_KEY: "replace-me"
  S3_SECRET_KEY: "replace-me"
  JWT_SECRET_KEY: "replace-me"
  GOOGLE_CLIENT_ID: "replace-me"
  GOOGLE_CLIENT_SECRET: "replace-me"
  NAVER_CLIENT_ID: "replace-me"
  NAVER_CLIENT_SECRET: "replace-me"
  NAVER_OPENAPI_CLIENT_ID: "replace-me"
  NAVER_OPENAPI_CLIENT_SECRET: "replace-me"
  NAVER_MAP_CLIENT_ID: "replace-me"
  NAVER_MAP_CLIENT_SECRET: "replace-me"
  MAIL_ADDRESS_MASTER: "replace-me"
  SMTP_HOST: "replace-me"
  SMTP_USERNAME: "replace-me"
  SMTP_PASSWORD: "replace-me"
  DART_API_KEY: ""
  KIS_APP_KEY: ""
  KIS_APP_SECRET: ""
